# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70498676d67879eb2f47810e01f31c0227e40946997caa004973051b3336d8a19af65542d6e07f675d8cfe5ac74fdac3f9c9755e8edc8c70550ac89e39e7e217

test:
  secret_key_base: 92b00628beae13084eae32e6d1b4a5232f3f0647f9c4d288b3bb4847d88d3f7e12561905ede65b08a05e25bf84540a23d5356826a24999472b9a31c693c56263

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
